### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by poeck**
Hey there! First off, thanks for this awesome library.

I noticed there weren't any TypeScript definitions included, so I went ahead and added them in this PR. Hopefully, this makes it even easier for TypeScript users to use this package. Let me know if anything needs tweaking!

### CODE REVIEW

**Comment by sagi** [comment]
Thanks @poeck . Apologies for responding only now. 

Can you please add the `types.d.ts` to the `.npmignore` file?

Otherwise LGTM.

**Comment by poeck** [comment]
Sure, I could do that - but are you supposed to do that? 🤔 

When adding a file to the `.npmignore` file it gets excluded from the npm registry, is that correct? As far as I know the type definitions also have to be on npm to work correctly.

**Comment by sagi** [comment]
It's OK.. I'll do it myself.

**Comment by sagi** [comment]
publish `@sagi.io/workers-kv@0.0.14`, thanks again! :)

**Comment by poeck** [comment]
Oh sorry, I thought you wanted me to "blacklist" the types in `.npmignore`, but I just realised you actually wanted me to explicitly "whitelist" it. 

Thank you! 🙏🏻

**Pull request merged**
